FROM openjdk:8-jdk-alpine
RUN apk update && apk add bash
VOLUME /tmp
ADD build/libs/local-mock-sms-api-1.3.0.jar app.jar
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]
